// <auto-generated />
using System;
using HealthESB.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HealthESB.API.Migrations
{
    [DbContext(typeof(HealthESBDbContext))]
    partial class HealthESBDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HealthESB.Domain.Entities.AvihangCitizenSessions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AvihangPersonInfoId")
                        .HasColumnType("bigint");

                    b.Property<int>("AvihangUserSessionId")
                        .HasColumnType("int");

                    b.Property<int?>("AvihangUserSessionsId")
                        .HasColumnType("int");

                    b.Property<string>("CitizenSessionId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NationalNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<int>("ResCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("ResDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResMessage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("providersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AvihangPersonInfoId");

                    b.HasIndex("AvihangUserSessionsId");

                    b.HasIndex("providersId");

                    b.ToTable("AvihangCitizenSessions");
                });

            modelBuilder.Entity("HealthESB.Domain.Entities.AvihangPersonInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("accountValidto")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("birthDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("cellPhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("countOfFamilyMember")
                        .HasColumnType("int");

                    b.Property<int>("coverageReferenceInter")
                        .HasColumnType("int");

                    b.Property<string>("gender")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("geoInfo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("isCovered")
                        .HasColumnType("bit");

                    b.Property<bool>("isReferenceable")
                        .HasColumnType("bit");

                    b.Property<string>("issuerType")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("lastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("lifeStatus")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("maritalStatus")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("memberImage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nationalNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<bool>("productName")
                        .HasColumnType("bit");

                    b.Property<string>("registrationStatus")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("relationType")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("responsibleFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("responsibleNN")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("specialAccount")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("zipCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("AvihangPersonInfos");
                });

            modelBuilder.Entity("HealthESB.Domain.Entities.AvihangPrescriptionSubscriptions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AvihangPrescriptionId")
                        .HasColumnType("int");

                    b.Property<long?>("AvihangPrescriptionsId")
                        .HasColumnType("bigint");

                    b.Property<int>("AvihangSubsciptionId")
                        .HasColumnType("int");

                    b.Property<int?>("AvihangSubsciptionsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AvihangPrescriptionsId");

                    b.HasIndex("AvihangSubsciptionsId");

                    b.ToTable("AvihangPrescriptionSubscriptions");
                });

            modelBuilder.Entity("HealthESB.Domain.Entities.AvihangPrescriptions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AvihangSamadId")
                        .HasColumnType("int");

                    b.Property<int?>("AvihangSamadsId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ReferenceFeedback")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ResCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("ResDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResMessage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<string>("TrackingCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AvihangSamadsId");

                    b.ToTable("AvihangPrescriptions");
                });

            modelBuilder.Entity("HealthESB.Domain.Entities.AvihangSamads", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AvihangCitizenSessionId")
                        .HasColumnType("int");

                    b.Property<int?>("AvihangCitizenSessionsId")
                        .HasColumnType("int");

                    b.Property<int>("AvihangUserSessionId")
                        .HasColumnType("int");

                    b.Property<int?>("AvihangUserSessionsId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReceiptPartnerId")
                        .HasColumnType("int");

                    b.Property<int>("ResCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("ResDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResMessage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SamadCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AvihangCitizenSessionsId");

                    b.HasIndex("AvihangUserSessionsId");

                    b.ToTable("AvihangSamads");
                });

            modelBuilder.Entity("HealthESB.Domain.Entities.AvihangSnackMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("objectName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("objectValue")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.ToTable("AvihangSnackMessages");
                });

            modelBuilder.Entity("HealthESB.Domain.Entities.AvihangSubsciptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AvihangSamadId")
                        .HasColumnType("int");

                    b.Property<int?>("AvihangSamadsId")
                        .HasColumnType("int");

                    b.Property<int>("BulkId")
                        .HasColumnType("int");

                    b.Property<string>("CheckCode")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Consumption")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConsumptionInstruction")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NationalNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NumberOfPeriod")
                        .HasColumnType("int");

                    b.Property<int>("ResCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("ResDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResMessage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("hasContract")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool>("isAllowed")
                        .HasColumnType("bit");

                    b.Property<int>("maxCoveredCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AvihangSamadsId");

                    b.ToTable("AvihangSubsciptions");
                });

            modelBuilder.Entity("HealthESB.Domain.Entities.AvihangTokens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("ResDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResMessage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TerminalId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Token")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("dto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ttl")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AvihangTokens");
                });

            modelBuilder.Entity("HealthESB.Domain.Entities.AvihangUserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("cPartyId")
                        .HasColumnType("int");

                    b.Property<string>("cellPhone")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("fullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("gender")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("internalId")
                        .HasColumnType("int");

                    b.Property<bool>("isTwoStep")
                        .HasColumnType("bit");

                    b.Property<int>("partnerId")
                        .HasColumnType("int");

                    b.Property<string>("partnerNN")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("partnerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AvihangUserInfos");
                });

            modelBuilder.Entity("HealthESB.Domain.Entities.AvihangUserSessions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AvihangUserInfoId")
                        .HasColumnType("int");

                    b.Property<int>("CpartyId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedicalCouncilNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<int>("ResCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("ResDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResMessage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SiamID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AvihangUserInfoId");

                    b.ToTable("AvihangUserSessions");
                });

            modelBuilder.Entity("HealthESB.Domain.Entities.Claims", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActionTitleEn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActionTitleFr")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ControlleEnTitile")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ControlleFaTitile")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ControllerEntityID")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("ControllerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Claims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionName = "Create",
                            ActionTitleEn = "Create",
                            ActionTitleFr = "ایجاد",
                            ControlleEnTitile = "PrescriptionBarcode",
                            ControlleFaTitile = "اقلام نسخه",
                            ControllerEntityID = 2,
                            ControllerName = "PrescriptionBarcode"
                        },
                        new
                        {
                            Id = 2,
                            ActionName = "ReActiveUid",
                            ActionTitleEn = "ReActiveUid",
                            ActionTitleFr = "فعال سازی مجدد",
                            ControlleEnTitile = "PrescriptionBarcode",
                            ControlleFaTitile = "اقلام نسخه",
                            ControllerEntityID = 2,
                            ControllerName = "PrescriptionBarcode"
                        },
                        new
                        {
                            Id = 3,
                            ActionName = "confirm",
                            ActionTitleEn = "confirm",
                            ActionTitleFr = "تایید نهایی اقلام",
                            ControlleEnTitile = "PrescriptionBarcode",
                            ControlleFaTitile = "اقلام نسخه",
                            ControllerEntityID = 2,
                            ControllerName = "PrescriptionBarcode"
                        },
                        new
                        {
                            Id = 4,
                            ActionName = "Create",
                            ActionTitleEn = "Create",
                            ActionTitleFr = "ایجاد نسخه",
                            ControlleEnTitile = "Prescription",
                            ControlleFaTitile = "نسخه",
                            ControllerEntityID = 1,
                            ControllerName = "Prescription"
                        },
                        new
                        {
                            Id = 5,
                            ActionName = "ReActiveByPrescriptionId",
                            ActionTitleEn = "ReActiveByPrescriptionId",
                            ActionTitleFr = "فعال سازی گروهی با شماره نسخه",
                            ControlleEnTitile = "PrescriptionBarcode",
                            ControlleFaTitile = "اقلام نسخه",
                            ControllerEntityID = 2,
                            ControllerName = "PrescriptionBarcode"
                        },
                        new
                        {
                            Id = 6,
                            ActionName = "GetPrescriptionActivity",
                            ActionTitleEn = "GetPrescriptionActivity",
                            ActionTitleFr = "تاریخچه ی درخواست های ارسالی",
                            ControlleEnTitile = "PrescriptionBarcodeDetailes",
                            ControlleFaTitile = "جزئیات اقلام نسخه",
                            ControllerEntityID = 3,
                            ControllerName = "PrescriptionBarcodeDetailes"
                        },
                        new
                        {
                            Id = 7,
                            ActionName = "GetPrescriptionBarcodeForActivation",
                            ActionTitleEn = "GetPrescriptionBarcodeForActivation",
                            ActionTitleFr = "جزئیات اقلام های نسخه های ارسالی",
                            ControlleEnTitile = "PrescriptionBarcodeDetailes",
                            ControlleFaTitile = "جزئیات اقلام نسخه",
                            ControllerEntityID = 3,
                            ControllerName = "PrescriptionBarcodeDetailes"
                        },
                        new
                        {
                            Id = 8,
                            ActionName = "CreateUser",
                            ActionTitleEn = "CreateUser",
                            ActionTitleFr = "ایجاد کاربر",
                            ControlleEnTitile = "AuthManagement",
                            ControlleFaTitile = "مدیریت کاربران",
                            ControllerEntityID = 4,
                            ControllerName = "AuthManagement"
                        },
                        new
                        {
                            Id = 9,
                            ActionName = "UpdateUser",
                            ActionTitleEn = "UpdateUser",
                            ActionTitleFr = "به روززسانی کاربر",
                            ControlleEnTitile = "AuthManagement",
                            ControlleFaTitile = "مدیریت کاربران",
                            ControllerEntityID = 4,
                            ControllerName = "AuthManagement"
                        },
                        new
                        {
                            Id = 10,
                            ActionName = "CreateRoles",
                            ActionTitleEn = "CreateRoles",
                            ActionTitleFr = "ایجاد نقش",
                            ControlleEnTitile = "AuthManagement",
                            ControlleFaTitile = "مدیریت کاربران",
                            ControllerEntityID = 4,
                            ControllerName = "AuthManagement"
                        },
                        new
                        {
                            Id = 11,
                            ActionName = "UpdateRoles",
                            ActionTitleEn = "UpdateRoles",
                            ActionTitleFr = "به روزرسانی نقش",
                            ControlleEnTitile = "AuthManagement",
                            ControlleFaTitile = "مدیریت کاربران",
                            ControllerEntityID = 4,
                            ControllerName = "AuthManagement"
                        },
                        new
                        {
                            Id = 12,
                            ActionName = "GetRoles",
                            ActionTitleEn = "GetRoles",
                            ActionTitleFr = "لیست نقش ها",
                            ControlleEnTitile = "AuthManagement",
                            ControlleFaTitile = "مدیریت کاربران",
                            ControllerEntityID = 4,
                            ControllerName = "AuthManagement"
                        },
                        new
                        {
                            Id = 13,
                            ActionName = "getUserRolesByUserIdAsync",
                            ActionTitleEn = "getUserRolesByUserIdAsync",
                            ActionTitleFr = "دریافت نقش های کاربر",
                            ControlleEnTitile = "AuthManagement",
                            ControlleFaTitile = "مدیریت کاربران",
                            ControllerEntityID = 4,
                            ControllerName = "AuthManagement"
                        },
                        new
                        {
                            Id = 14,
                            ActionName = "getUsersAsync",
                            ActionTitleEn = "getUsersAsync",
                            ActionTitleFr = "لیست کاربران",
                            ControlleEnTitile = "AuthManagement",
                            ControlleFaTitile = "مدیریت کاربران",
                            ControllerEntityID = 4,
                            ControllerName = "AuthManagement"
                        },
                        new
                        {
                            Id = 15,
                            ActionName = "GetClaimList",
                            ActionTitleEn = "GetClaimList",
                            ActionTitleFr = "دریافت لیست دسترسی ها",
                            ControlleEnTitile = "AuthManagement",
                            ControlleFaTitile = "مدیریت کاربران",
                            ControllerEntityID = 4,
                            ControllerName = "AuthManagement"
                        },
                        new
                        {
                            Id = 16,
                            ActionName = "GetUserClaims",
                            ActionTitleEn = "GetUserClaims",
                            ActionTitleFr = "لیست دسترسی های کاربر",
                            ControlleEnTitile = "AuthManagement",
                            ControlleFaTitile = "مدیریت کاربران",
                            ControllerEntityID = 4,
                            ControllerName = "AuthManagement"
                        },
                        new
                        {
                            Id = 17,
                            ActionName = "AssignRoleToClaims",
                            ActionTitleEn = "AssignRoleToClaims",
                            ActionTitleFr = "اختصاص دسترسی به نقش",
                            ControlleEnTitile = "AuthManagement",
                            ControlleFaTitile = "مدیریت کاربران",
                            ControllerEntityID = 4,
                            ControllerName = "AuthManagement"
                        },
                        new
                        {
                            Id = 18,
                            ActionName = "RemoveClaimsFromRole",
                            ActionTitleEn = "RemoveClaimsFromRole",
                            ActionTitleFr = "حذف دسترسی از نقش",
                            ControlleEnTitile = "AuthManagement",
                            ControlleFaTitile = "مدیریت کاربران",
                            ControllerEntityID = 4,
                            ControllerName = "AuthManagement"
                        },
                        new
                        {
                            Id = 19,
                            ActionName = "GetRoleClaims",
                            ActionTitleEn = "GetRoleClaims",
                            ActionTitleFr = "لیست دسترسی های نقش",
                            ControlleEnTitile = "AuthManagement",
                            ControlleFaTitile = "مدیریت کاربران",
                            ControllerEntityID = 4,
                            ControllerName = "AuthManagement"
                        });
                });

            modelBuilder.Entity("HealthESB.Domain.Entities.Prescription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BasicInsurance")
                        .HasColumnType("int");

                    b.Property<int>("ComplementaryInsurance")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedicalCouncilNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OutErrorCode")
                        .HasColumnType("int");

                    b.Property<string>("OutErrorMessage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("OutPrescriptionId")
                        .HasColumnType("bigint");

                    b.Property<string>("PatientGivenName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PatientNationalCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PatientSurname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PharmacyGln")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhysicianGivenName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhysicianSurName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Prescription");
                });

            modelBuilder.Entity("HealthESB.Domain.Entities.PrescriptionBarcode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BarcodeUid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GenericCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OutErrorCode")
                        .HasColumnType("int");

                    b.Property<string>("OutErrorMessage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PrescriptionBarcodeStatusId")
                        .HasColumnType("int");

                    b.Property<long>("PrescriptionId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReCheckCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PrescriptionBarcodeStatusId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PrescriptionBarcode");
                });

            modelBuilder.Entity("HealthESB.Domain.Entities.PrescriptionBarcodeDetailes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BarcodeUid")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BatchCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnglishName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Expiration")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GenericCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Irc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Manufacturing")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PersianName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PrescriptionBarcodeDetailesTypesId")
                        .HasColumnType("int");

                    b.Property<long>("PrescriptionBarcodeId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ProductType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusMessage")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TrackingCode")
                        .HasColumnType("int");

                    b.Property<string>("Uid")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("UnitConsumed")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PrescriptionBarcodeDetailesTypesId");

                    b.HasIndex("PrescriptionBarcodeId");

                    b.ToTable("PrescriptionBarcodeDetailes");
                });

            modelBuilder.Entity("HealthESB.Domain.Entities.PrescriptionBarcodeDetailesType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PrescriptionBarcodeDetailesType");
                });

            modelBuilder.Entity("HealthESB.Domain.Entities.PrescriptionBarcodeStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PrescriptionBarcodeStatus");
                });

            modelBuilder.Entity("HealthESB.Domain.Entities.ProviderApis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<int?>("ProvidersId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProvidersId");

                    b.ToTable("ProviderApis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "ec279046-7f84-428d-ac8a-e7a3a7305a14",
                            Name = "ثبت نسخه",
                            ProviderId = 1,
                            Url = "registerprescription"
                        },
                        new
                        {
                            Id = 2,
                            Key = "ac89bf71-844c-4d5c-8472-185ee0413d61",
                            Name = "ثبت داروهای نسخه",
                            ProviderId = 1,
                            Url = "checksinglebarcodeuid"
                        },
                        new
                        {
                            Id = 3,
                            Key = "69869aa7-c493-48eb-acf4-bd21f186672b",
                            Name = "فعال سازی مجدد ",
                            ProviderId = 1,
                            Url = "reactivateuid"
                        },
                        new
                        {
                            Id = 4,
                            Key = "",
                            Name = "وب سرویس واکشی توکن",
                            ProviderId = 2,
                            Url = "auth/token/fetch"
                        },
                        new
                        {
                            Id = 5,
                            Key = "",
                            Name = "وب سرویس ایجاد نشست کاربر",
                            ProviderId = 2,
                            Url = "internal/session/cparty/open"
                        },
                        new
                        {
                            Id = 6,
                            Key = "",
                            Name = "وب سرویس ایجاد نشست شهروند",
                            ProviderId = 2,
                            Url = "auth/session/citizen/open"
                        },
                        new
                        {
                            Id = 7,
                            Key = "",
                            Name = "وب سرویس ایجاد کد سماد الکترونیک",
                            ProviderId = 2,
                            Url = "samad/electronic/generate"
                        },
                        new
                        {
                            Id = 8,
                            Key = "",
                            Name = "وب سرویس ثبت نسخه",
                            ProviderId = 2,
                            Url = "prescription/save"
                        },
                        new
                        {
                            Id = 9,
                            Key = "",
                            Name = "وب سرویس بررسی ریز نسخه تجویز",
                            ProviderId = 2,
                            Url = "subscription/check/order"
                        });
                });

            modelBuilder.Entity("HealthESB.Domain.Entities.Providers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Providers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseUrl = "http://api.ttac.ir/insurances/test/v74/",
                            Name = "سازمان غذا و دارو",
                            Password = "ghkZKzBwdy",
                            UserName = "bimeh_salamat"
                        },
                        new
                        {
                            Id = 2,
                            BaseUrl = "http://test.ihio.gov.ir/erx-core/v3/service/",
                            Name = "سرویس های نسخه الکترونیک",
                            Password = "9123085676",
                            UserName = "HDK_hasanlou_test"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("HealthESB.Domain.Entities.AvihangCitizenSessions", b =>
                {
                    b.HasOne("HealthESB.Domain.Entities.AvihangPersonInfo", "AvihangPersonInfo")
                        .WithMany()
                        .HasForeignKey("AvihangPersonInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthESB.Domain.Entities.AvihangUserSessions", "AvihangUserSessions")
                        .WithMany()
                        .HasForeignKey("AvihangUserSessionsId");

                    b.HasOne("HealthESB.Domain.Entities.Providers", "providers")
                        .WithMany()
                        .HasForeignKey("providersId");

                    b.Navigation("AvihangPersonInfo");

                    b.Navigation("AvihangUserSessions");

                    b.Navigation("providers");
                });

            modelBuilder.Entity("HealthESB.Domain.Entities.AvihangPrescriptionSubscriptions", b =>
                {
                    b.HasOne("HealthESB.Domain.Entities.AvihangPrescriptions", "AvihangPrescriptions")
                        .WithMany()
                        .HasForeignKey("AvihangPrescriptionsId");

                    b.HasOne("HealthESB.Domain.Entities.AvihangSubsciptions", "AvihangSubsciptions")
                        .WithMany()
                        .HasForeignKey("AvihangSubsciptionsId");

                    b.Navigation("AvihangPrescriptions");

                    b.Navigation("AvihangSubsciptions");
                });

            modelBuilder.Entity("HealthESB.Domain.Entities.AvihangPrescriptions", b =>
                {
                    b.HasOne("HealthESB.Domain.Entities.AvihangSamads", "AvihangSamads")
                        .WithMany()
                        .HasForeignKey("AvihangSamadsId");

                    b.Navigation("AvihangSamads");
                });

            modelBuilder.Entity("HealthESB.Domain.Entities.AvihangSamads", b =>
                {
                    b.HasOne("HealthESB.Domain.Entities.AvihangCitizenSessions", "AvihangCitizenSessions")
                        .WithMany()
                        .HasForeignKey("AvihangCitizenSessionsId");

                    b.HasOne("HealthESB.Domain.Entities.AvihangUserSessions", "AvihangUserSessions")
                        .WithMany()
                        .HasForeignKey("AvihangUserSessionsId");

                    b.Navigation("AvihangCitizenSessions");

                    b.Navigation("AvihangUserSessions");
                });

            modelBuilder.Entity("HealthESB.Domain.Entities.AvihangSubsciptions", b =>
                {
                    b.HasOne("HealthESB.Domain.Entities.AvihangSamads", "AvihangSamads")
                        .WithMany()
                        .HasForeignKey("AvihangSamadsId");

                    b.Navigation("AvihangSamads");
                });

            modelBuilder.Entity("HealthESB.Domain.Entities.AvihangUserSessions", b =>
                {
                    b.HasOne("HealthESB.Domain.Entities.AvihangUserInfo", "AvihangUserInfo")
                        .WithMany()
                        .HasForeignKey("AvihangUserInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvihangUserInfo");
                });

            modelBuilder.Entity("HealthESB.Domain.Entities.PrescriptionBarcode", b =>
                {
                    b.HasOne("HealthESB.Domain.Entities.PrescriptionBarcodeStatus", "PrescriptionBarcodeStatus")
                        .WithMany()
                        .HasForeignKey("PrescriptionBarcodeStatusId");

                    b.HasOne("HealthESB.Domain.Entities.Prescription", "Prescription")
                        .WithMany()
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescription");

                    b.Navigation("PrescriptionBarcodeStatus");
                });

            modelBuilder.Entity("HealthESB.Domain.Entities.PrescriptionBarcodeDetailes", b =>
                {
                    b.HasOne("HealthESB.Domain.Entities.PrescriptionBarcodeDetailesType", "PrescriptionBarcodeDetailesTypes")
                        .WithMany()
                        .HasForeignKey("PrescriptionBarcodeDetailesTypesId");

                    b.HasOne("HealthESB.Domain.Entities.PrescriptionBarcode", "PrescriptionBarcode")
                        .WithMany()
                        .HasForeignKey("PrescriptionBarcodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrescriptionBarcode");

                    b.Navigation("PrescriptionBarcodeDetailesTypes");
                });

            modelBuilder.Entity("HealthESB.Domain.Entities.ProviderApis", b =>
                {
                    b.HasOne("HealthESB.Domain.Entities.Providers", "Providers")
                        .WithMany()
                        .HasForeignKey("ProvidersId");

                    b.Navigation("Providers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
